# ---------- WHAT THINGS DO WE WANT TO DO WITH STRINGS? ---------- #

# CONVERT NUMBERS TO STRINGS
# CONVERT STRINGS TO NUMBERS
# DETERMINE HOW LONG A STRING IS
# GET PART OF A LONGER STRING
# CONVERT A STRING TO ALL UPPER CASE
# CONVERT STRING TO ALL LOWER CASE
# REPLACE PART OF A STRING WITH ANOTEHR STRING
# REMOVE WHITE SPACE FROM THE BEGINNING AND / OR END OF A STRING
# SEARCH A STRING TO SEE AT WHAT LOCATION IT CONTAINS A STRING
# CHECK TO SEE IS A STRING DOES / DOES NOTR CONTAIN ANOTHER STRING
# CHECK TO SEE IF A STRING IS UPPER CASE OR LOWER CASE
# DIVIDE A STRING INTO MANY STRINGS BASED ON A SINGLE CHARACTER